### ISSUE TITLE
Generate code based on version rather than cfg

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/const_fn#15]
something like:

```rust
#[const_fn(1.36)]
const fn foo() {
    // ...
}
```

**Comment by jhpratt** [comment]
Even more powerful, with the use of autocfg, it may be possible to _automatically_ determine if the function can be `const`. This would allow use on nightlies and betas similarly.

**Comment by taiki-e** [comment]
> it may be possible to _automatically_ determine if the function can be `const`.

Interesting, but does it actually seem like you have to compile the whole crate per `const_fn` attribute (as the function may depend on other items in the crate)?

**Comment by jhpratt** [comment]
Yeah, that would likely be the case now that you bring it up. Disregard 😄

**Comment by taiki-e** [comment]
Published 0.4.0 which fixes this issue.
